greeter:
  medgelabs:
    channelId: 62232210
    messageFormat: "Welcome to the lab, @%s!"
  sorceryandsarcasm:
    messageFormat: "@%s sorcer19Hype"
  spookyghostmachine:
    messageFormat: "@%s spooky127Hype"
