greeter:
  medgelabs:
    messageFormat: "Welcome to the lab, %s"
  sorceryandsarcasm:
    messageFormat: "%s sorcer19Hype Welcome!"
  spookyghostmachine:
    messageFormat: "%s spooky127Hype Welcome!"
